'''
1.02.E01a
Monsters II

required:
TODO

result:
TODO
'''

"""
A Nested Loop Structure
Nested loops iterate values u and v over intervals from zero to two pi, resulting in Points in rows and columns. At each iteration, a Point is constructed in three-dimensions and stored in a list. Note that the list is re-initialized after every cycle of a u-value, and does not persist through the entire script.
"""
for u in Interval.twopi()/count_u:
    pts = []
    for v in Interval.twopi()/count_v:
        x = ( (a+1)*cos(u) + cos(u*(a+1)) ) * v
        y = ( (a+1)*sin(u) + sin(u*(a+1)) ) * v
        z = 3.0*sin(v*b)
        pts.append(Point(x,y,z))
        
"""
A Static Method
The centroid of a collection of Points may be determined using the appropriate static method.
"""
cent = Point.centroid(pts)

"""
Segment Construction
For each Point stored, create a Segment between it and a Point generated by interpolation (a static method of the Point class). Note that this loop occurs within the u-loop, and will cycle for each row of Points.
"""
    for spt in pts:
        ept = Point.interpolate(spt,cent,0.25)
        seg = Segment(spt,ept)
        clr = Color.HSB(u/math.pi,1,1)
        seg.set_color(clr)
        out.put(seg)

        